image: python:3.8-alpine
    
pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install myst-parser
  - pip install sphinx-rtd-theme
  - pip install sphinxcontrib-mermaid
  - sphinx-build -b html ./documentation public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH