image: python:3.7-alpine

test:
  stage: test
  script:
  - pip install -U sphinx
  - pip install myst-parser
  - pip install sphinx-rtd-theme
  - pip install sphinxcontrib-mermaid
  - pip install npm
  - sphinx-build -b html ./documentation public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  jobs:
    post_install:
      - npm install -g @mermaid-js/mermaid-cli
    
pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install myst-parser
  - pip install sphinx-rtd-theme
  - pip install sphinxcontrib-mermaid
  - pip install npm
  - sphinx-build -b html ./documentation public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  jobs:
    post_install:
      - npm install -g @mermaid-js/mermaid-cli