image: python:3.8-alpine
    
pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install -r ./documentation/requirements.txt
  - sphinx-build -b html ./documentation public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"