name: documentation

on: [push, pull_request, workflow_dispatch]



jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Install python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install -r documentation/requirements.txt

      # Sphinx build
      - name: Sphinx build
        if: ${{ github.event_name == 'push' }}
        run: |
          sphinx-build documentation/content documentation/_build

      # Stage all deployed assets in _gh-pages
      - name: Copy deployment data to _gh-pages/
        if: ${{ github.event_name == 'push' }}
        run:
          rsync -a documentation/_build/ _gh-pages/

      # Add the .nojekyll file
      - name: nojekyll
        if: ${{ github.event_name == 'push' }}
        run: |
          touch _gh-pages/.nojekyll

      # Save artifact for the next step.
      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: gh-pages-build
          path: _gh-pages/          


  # Deploy in a separate job so that write permissions are restricted
  # to the minimum steps.
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-docs
    # This if can't use the env context - find better way later.
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: write

    steps:

      # Deploy to pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _gh-pages/
          force_orphan: true
